routes/web.php
<?php

use App\Http\Controllers\ActorController;
use App\Http\Controllers\MovieController;
use App\Http\Controllers\SearchController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('tinker', function () {
    // removed some unused code.
});

Route::get('/movies', [MovieController::class, 'index'])->name('movies.index');

// show form
Route::get('/movies/create', [MovieController::class, 'create'])->name('movies.create');

// handle new movie form
Route::post('/movies', [MovieController::class, 'store'])->name('movies.store');

Route::get('/movies/{movie}', [MovieController::class, 'show'])->name('movies.show');

Route::post('/movies/{movie}/ratings', [MovieController::class, 'storeRating'])->name('ratings.store');

Route::resource('actors', ActorController::class);

Route::get('/search', SearchController::class)->name('search');







Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return Inertia\Inertia::render('Dashboard');
})->name('dashboard');

resources/views/movies/create.blade.php
@extends('layouts/master')

@section('content')

	<div class="row">
		<div class="col-md-7 col-lg-6">

			<div class="card">
				<div class="card-body">
					<form action="{{ route('movies.store') }}" method="post">
						@csrf
						<div class="form-group">
							<label for="titleInput">Title</label>
							<input value="{{ old('title') }}" name="title" type="text"
							class="form-control @error('title') is-invalid @enderror" id="titleInput" aria-describedby="titleHelp">
							<small id="titleHelp" class="form-text text-muted">This is the title for the movie you are creating</small>

							@error('title')
								<div class="invalid-feedback">
									{{ $message }}
								</div>
							@enderror
						</div>
						<div class="form-group">
							<label for="descriptionInput">Description</label>
							<input value="{{ old('description') }}" name="description" type="text"
							class="form-control @error('description') is-invalid @enderror" id="descriptionInput">

							@error('description')
								<div class="invalid-feedback">
									{{ $message }}
								</div>
							@enderror
						</div>
						<button type="submit" class="btn btn-primary">Create</button>
					</form>
				</div>
			</div>


		</div>
		<div class="col-md-5 col-lg-6">
			<div class="alert alert-info">
				<h3>
					Movies are awesome!
				</h3>
				<p>
					Use this form to record a new movie in our DB!
				</p>
			</div>
		</div>
	</div>


@endsection

resources/views/movies/index.blade.php
@extends('layouts/master')

@section('content')

	{{ $movies->links() }}

	@foreach($movies as $movie)
		
		<h1>
			<a href="{{ $movie->url() }}">
				{{ $movie->title }}
			</a>
		</h1>
		<p>
			{{ $movie->description }}
		</p>


	@endforeach

@endsection

resources/views/movies/show.blade.php
@extends('layouts/master')

@section('content')

	<div class="row">
		<div class="col-md-3">
			<div class="card">
				<img src="{{ $movie->poster }}" class="card-img-top" alt="Movie poster">

				<div class="card-body">
					<h2>
						{{ $movie->title }}
					</h2>

					<p>
						{{ $movie->description }}
					</p>
				</div>
			</div>
		</div>
		<div class="col-md-6">

			<h3>
				Ratings
			</h3>
			<h5>
				This was rated {{ intval($movie->ratings()->avg('score')) }} out of {{ $movie->ratings->count() }} total ratings
			</h5>

			<p>
				All users that rated this movie:
				@foreach($movie->ratings as $rating)
					{{ $rating->user->name }}
				@endforeach
			</p>

			<form method="post" action="{{ route('ratings.store', $movie) }}">
				@csrf
				<select name="score">
					<option value="1">Hated it</option>
					<option value="2">Disliked it</option>
					<option value="3">Meh</option>
					<option value="4">Liked it</option>
					<option value="5">Loved it</option>
				</select>

				<input type="submit" value="Rate this movie!">
			</form>

			<h3>
				Cast
			</h3>

			@foreach($movie->actors as $actor)
				<h5>
					{{ $actor->name }}
				</h5>
				<h5>
					This actor has starred in {{ $actor->movies->count() }} movies
				</h5>

				@foreach($actor->movies as $otherMovie)
					<p>
						<a href="{{ $otherMovie->url() }}">
							{{ $otherMovie->title }}
						</a>
					</p>
				@endforeach

                <a href="{{ route('actors.show', $actor) }}">
				    <img src="{{ $actor->pic }}" alt="Picture of {{ $actor->full_name }}">
                </a>
			@endforeach
		</div>
	</div>

@endsection